version: '3'

services:
  mongodb:
    build: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  
  nodejs-app:
    build: nodejs
      context: nodejs
      args:
          STATE: PRODUCTION
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    depends_on:
      - mongodb
    links:
      - mongodb