version: '3'

services:
  mongodb:
    build:
      context: ./mongo
      dockerfile: Dockerfile.mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  
  nodejs-app:
    build:
      context: ./nodejs
      dockerfile: Dockerfile.nodejs
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    depends_on:
      - mongodb
    links:
      - mongodb