
Vagrant.configure("2") do |config|

    # Do not pay attention to this parameter
    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vm.provider :virtualbox do |vb|
        config.vbguest.auto_update = false
      end
    end
  
    config.ssh.insert_key = false
    
    # Define the nodejs_server VM
    config.vm.define "nodejs_server" do |server|
      # Specify the Vagrant box to use
      server.vm.box = "ubuntu/bionic64"
      # Specify the VM ip address
      config.vm.network "forwarded_port", guest: 3000, host: 3000
      # Specify the VM specs when using the Virtualbox provisioner
      server.vm.provider "virtualbox" do |vb|
        vb.name =  "nodejs.server.local"
        # VM RAM in MB
        vb.memory = 2048
        # VM CPUs
        vb.cpus = 1
      end
      config.vm.provider "vmware_desktop" do |vmware|
        vmware.vmx["memsize"] = "2048"
        vmware.vmx["numvcpus"] = "1"
      end
    end
  
    # Use Vagrant Ansible provisioner
    config.vm.provision "ansible_local" do |ansible|
      # The path to the playbooks entry point
      ansible.version = "2.10"
      ansible.playbook = "ansible/playbooks/install.yml"
      # Only run the roles with these tags
      ansible.tags = "install"
    end
  
  end
  